// PATH: src/styles/base.web.js
import { StyleSheet } from 'react-native';
import { AppTheme } from './theme';

export default StyleSheet.create({
  overlay: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 24,
    maxWidth: 900,
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  background: {
    flex: 1,
    backgroundColor: AppTheme.colors.background,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: AppTheme.colors.text,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
    color: AppTheme.colors.text,
  },
  label: {
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 6,
    fontSize: 16,
    color: AppTheme.colors.text,
    alignSelf: 'flex-start',
    maxWidth: 400,
  },
  formInput: {
    borderWidth: 1,
    borderColor: AppTheme.colors.placeholder,
    borderRadius: AppTheme.roundness,
    padding: 12,
    marginBottom: 16,
    backgroundColor: AppTheme.colors.surface,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    fontSize: 16,
  },
  button: {
    backgroundColor: AppTheme.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: AppTheme.roundness,
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginBottom: 16,
    cursor: 'pointer',
  },
  buttonText: {
    color: AppTheme.colors.surface,
    fontWeight: '700',
    fontSize: 16,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 10,
  },
  activeTab: {
    backgroundColor: AppTheme.colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: AppTheme.roundness,
    color: AppTheme.colors.surface,
    cursor: 'pointer',
  },
  inactiveTab: {
    backgroundColor: '#f0f0f0',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: AppTheme.roundness,
    color: '#444',
    cursor: 'pointer',
  },
  listItem: {
    backgroundColor: AppTheme.colors.surface,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: AppTheme.roundness,
    padding: 16,
    marginBottom: 12,
    width: '100%',
    maxWidth: 700,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  itemBox: {
    padding: 16,
    borderRadius: AppTheme.roundness,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 12,
    backgroundColor: AppTheme.colors.surface,
    maxWidth: 700,
    width: '100%',
    alignSelf: 'center',
  },
  subText: {
    fontSize: 16,
    color: AppTheme.colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  price: {
    color: 'green',
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 8,
    textAlign: 'center',
  },
  picker: {
    borderWidth: 1,
    borderColor: AppTheme.colors.placeholder,
    borderRadius: AppTheme.roundness,
    padding: 10,
    marginBottom: 16,
    backgroundColor: AppTheme.colors.surface,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  offerCard: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.roundness,
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 20,
    marginBottom: 16,
    width: '100%',
    maxWidth: 700,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  offerTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 6,
    color: AppTheme.colors.text,
  },
  offerDetail: {
    fontSize: 16,
    marginBottom: 6,
    color: AppTheme.colors.text,
  },
  sectionBox: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.roundness,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
});