// PATH: src/styles/base.native.js
import { StyleSheet } from 'react-native';
import { AppTheme } from './theme';

export default StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: 'cover',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.4)',
    padding: 16,
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    color: AppTheme.colors.text,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10,
  },
  activeTab: {
    backgroundColor: AppTheme.colors.primary,
    padding: 10,
    marginHorizontal: 5,
    borderRadius: AppTheme.roundness,
  },
  inactiveTab: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    marginHorizontal: 5,
    borderRadius: AppTheme.roundness,
  },
  itemBox: {
    padding: 12,
    borderRadius: AppTheme.roundness,
    borderWidth: 1,
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.8)',
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  button: {
    backgroundColor: AppTheme.colors.primary,
    padding: 10,
    borderRadius: AppTheme.roundness,
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginBottom: 10,
  },
  buttonText: {
    color: AppTheme.colors.surface,
    fontWeight: 'bold',
  },
  subText: {
    fontSize: 16,
    color: AppTheme.colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  listItem: {
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: AppTheme.roundness,
    padding: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    maxWidth: 500,
    alignSelf: 'center',
    width: '100%',
  },
  price: {
    color: 'green',
    fontSize: 16,
    fontWeight: 'bold',
    marginVertical: 8,
  },
  label: {
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 6,
    fontSize: 16,
    textAlign: 'center',
    color: AppTheme.colors.text,
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  picker: {
    borderWidth: 1,
    borderColor: AppTheme.colors.placeholder,
    borderRadius: AppTheme.roundness,
    padding: 8,
    marginBottom: 16,
    backgroundColor: '#f9f9f9',
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  card: {
    backgroundColor: AppTheme.colors.surface,
    padding: 16,
    borderRadius: AppTheme.roundness + 4,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    maxWidth: 500,
    alignSelf: 'center',
    width: '100%',
  },
  offerCard: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.roundness + 4,
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    maxWidth: 500,
    alignSelf: 'center',
    width: '100%',
  },
  offerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
    color: AppTheme.colors.text,
  },
  offerDetail: {
    marginBottom: 6,
    fontSize: 14,
    color: AppTheme.colors.text,
  },
  sectionBox: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.roundness + 4,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    maxWidth: 500,
    alignSelf: 'center',
    width: '100%',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: AppTheme.colors.text,
  },
  formInput: {
    borderWidth: 1,
    borderColor: AppTheme.colors.placeholder,
    borderRadius: AppTheme.roundness,
    padding: 10,
    marginBottom: 10,
    backgroundColor: AppTheme.colors.surface,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
});